# Loss Functions

In [1]:
import torch
import torch.nn as nn

### Mean-Squared Loss

In [2]:
prediction = torch.randn(4,5)
prediction

tensor([[-0.3609,  0.8666, -0.2309,  2.0283,  1.1034],
        [ 0.3700, -2.0589,  0.0689, -0.3031, -0.3467],
        [ 1.2822,  2.0098,  0.7484, -0.1459, -1.5341],
        [ 1.6089,  2.8434, -0.8138, -0.3898,  1.8719]])

In [3]:
label = torch.randn(4,5)
label

tensor([[ 1.7978, -0.0221, -0.2008, -0.1188,  1.5822],
        [-0.3671, -0.6765,  1.6402,  1.7498, -1.2393],
        [-0.4367, -0.5027,  1.2113, -0.3810, -1.5282],
        [ 0.3049,  0.7158,  2.6476,  0.7302, -0.3338]])

In [4]:
mse_none = nn.MSELoss(reduction='none')

In [5]:
loss = mse_none(prediction,label)
loss

tensor([[4.6603e+00, 7.8976e-01, 9.0882e-04, 4.6099e+00, 2.2926e-01],
        [5.4339e-01, 1.9110e+00, 2.4689e+00, 4.2143e+00, 7.9661e-01],
        [2.9545e+00, 6.3124e+00, 2.1422e-01, 5.5269e-02, 3.4614e-05],
        [1.7003e+00, 4.5270e+00, 1.1981e+01, 1.2544e+00, 4.8651e+00]])

In [6]:
mse_mean = nn.MSELoss(reduction='mean')

In [7]:
loss = mse_mean(prediction,label)
loss

tensor(2.7044)

#### Calculating the mse directly...

In [8]:
((prediction-label)**2).mean()

tensor(2.7044)

### Binary Cross-Entropy Loss

In [9]:
prediction

tensor([[-0.3609,  0.8666, -0.2309,  2.0283,  1.1034],
        [ 0.3700, -2.0589,  0.0689, -0.3031, -0.3467],
        [ 1.2822,  2.0098,  0.7484, -0.1459, -1.5341],
        [ 1.6089,  2.8434, -0.8138, -0.3898,  1.8719]])

In [10]:
label = torch.zeros(4,5).random_(0,2)  # 1+1 = 2 specifies 1 has highest index (take on values of 0 or 1)
label

tensor([[1., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.],
        [1., 1., 0., 1., 1.],
        [1., 0., 0., 0., 0.]])

#### For binary cross-entropy loss, we need a sigmoid function.

In [11]:
sigmoid = nn.Sigmoid()

In [12]:
bce = nn.BCELoss(reduction='mean')

In [13]:
bce(sigmoid(prediction),label)

tensor(0.8326)

In [14]:
bces = nn.BCEWithLogitsLoss(reduction='mean')  # don't need the sigmoid function here
bces(prediction,label)

tensor(0.8326)

#### Calculating the BCE directly...

In [15]:
import numpy as np
x = sigmoid(prediction).numpy()  # get the sigmoid of x so that we can use logit functions
y = label.numpy()                # convert 'prediction' and 'label' from tensor to numpy array

In [16]:
# not an efficient way of accomplishing the task

loss_values=[]  # start with empty list.  
for i in range(len(x)):
    batch_loss=[]
    for j in range(len(x[0])):  # x[0] is the first row of x
        if y[i][j]==1:
            loss = -np.log(x[i][j])
        else:
            loss = -np.log(1-x[i][j])        
        batch_loss.append(loss)
    loss_values.append(batch_loss)

In [17]:
np.mean(loss_values)

0.8326199400592739

In [18]:
# a more compact way of writing the code

loss_values=[]  # start with empty list.  
for i in range(len(x)):
    batch_loss=[]
    for j in range(len(x[0])):  # x[0] is the first row of x
        batch_loss.append(-np.log(x[i][j]) if y[i][j]==1 else -np.log(1-x[i][j])) 
    loss_values.append(batch_loss)

In [19]:
np.mean(loss_values)

0.8326199400592739