# PyTorch Tensors

In [1]:
import torch

In [2]:
#This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [3]:
#This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [4]:
#The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [5]:
#Get the height/number of rows of b
print(b.shape[0])

4


In [6]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#c = torch.tensor([2,2,1], dtype = torch.float)

In [7]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d = torch.tensor([2,2,1], dtype = torch.double)

In [8]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [9]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [10]:
print(c.mean())

tensor(2.5833)


In [11]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [12]:
print(c.std())

tensor(1.5050)


In [13]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [14]:
#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
#We can even reshape 3D tensors
print('\n')
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channles,rows,columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12))  # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[-7.1223e-01,  8.2832e-01, -2.0221e-01, -5.5233e-01],
         [-1.2982e+00,  9.6927e-01, -2.4172e-03,  3.3115e-01],
         [-2.1193e+00, -1.3864e+00, -3.1404e+00, -3.9098e-01]],

        [[ 2.8147e-01, -7.4502e-01,  1.4883e-01,  6.8824e-01],
         [-1.0310e-01,  4.6670e-01, -2.1574e+00,  4.6517e-02],
         [ 5.9686e-01, -1.4360e+00, -2.0079e-01,  7.1916e-01]]])
tensor([[-7.1223e-01,  8.2832e-01, -2.0221e-01, -5.5233e-01, -1.2982e+00,
          9.6927e-01, -2.4172e-03,  3.3115e-01, -2.1193e+00, -1.3864e+00,
         -3.1404e+00, -3.9098e-01],
        [ 2.8147e-01, -7.45

In [15]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.6810, 0.5422, 0.3563, 0.8437],
        [0.0166, 0.7417, 0.4468, 0.4866],
        [0.3015, 0.1197, 0.1568, 0.7974],
        [0.2651, 0.5243, 0.5291, 0.5134]])


In [16]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1 
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-0.6684, -1.3886,  0.4647, -0.4275],
        [-1.1174,  0.1978,  1.1261,  1.1560],
        [ 0.6926,  0.6318,  1.2486,  0.1509],
        [-0.4198, -0.1264, -1.9949,  0.8959]])
torch.float32


In [17]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6,10, (5,))
print(in_array)
print(in_array.dtype)

tensor([8, 8, 9, 9, 6])
torch.int64


In [18]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[9, 7, 9],
        [9, 8, 6],
        [8, 9, 9]])


In [19]:
#Get the number of elemetns in in_array
print(torch.numel(in_array))
#Get the number of elemetns in in_array
print(torch.numel(in_array2))

5
9


In [20]:
#Construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
#Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [21]:
r2_like = torch.randn_like(r2, dtype=torch.double)    # Convert the data type of the tensor
print(r2_like)

tensor([[ 0.2287, -0.4044, -0.1114, -0.8865],
        [ 0.1246,  1.6313, -0.2816,  0.3814],
        [-0.2905,  0.2608, -1.4721, -0.0255],
        [ 0.4436,  0.7060, -0.7873,  0.0300]], dtype=torch.float64)


In [22]:
#Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[ 0.0126, -0.8464,  0.8211,  0.4162],
        [-1.1008,  0.9395,  1.5729,  1.6427],
        [ 0.9941,  0.7516,  1.4054,  0.9483],
        [-0.1547,  0.3979, -1.4658,  1.4093]])


In [23]:
#In-place addition (change the value of r2)
r2.add_(r)    
print(r2)

tensor([[ 0.0126, -0.8464,  0.8211,  0.4162],
        [-1.1008,  0.9395,  1.5729,  1.6427],
        [ 0.9941,  0.7516,  1.4054,  0.9483],
        [-0.1547,  0.3979, -1.4658,  1.4093]])


In [24]:
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([-0.8464,  0.9395,  0.7516,  0.3979])
tensor([[ 0.0126, -0.8464],
        [-1.1008,  0.9395],
        [ 0.9941,  0.7516],
        [-0.1547,  0.3979]])
tensor([[ 0.0126, -0.8464,  0.8211,  0.4162],
        [-1.1008,  0.9395,  1.5729,  1.6427],
        [ 0.9941,  0.7516,  1.4054,  0.9483]])
tensor(0.9483)
0.9483034014701843
tensor([0.9941, 0.7516, 1.4054, 0.9483])


## Numpy Bridge

In [25]:
import numpy as np

In [26]:
#Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
#See how the numpy array changed their value.
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
#Converting NumPy Array to Torch Tensor
#See how changing the np array changed the Torch Tensor automatically
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
#Move the tensor to the GPU
# r2 = r2.cuda()
print(r2)

tensor([[ 0.0126, -0.8464,  0.8211,  0.4162],
        [-1.1008,  0.9395,  1.5729,  1.6427],
        [ 0.9941,  0.7516,  1.4054,  0.9483],
        [-0.1547,  0.3979, -1.4658,  1.4093]])


In [29]:
#Provide Easy switching between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

False


In [30]:
#You can also convert a list to a tensor
a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


In [31]:
data =  [[1., 2.], [3., 4.],
         [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


## Tensor Concatenation

In [32]:
#Tensor Concatenation 
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
#Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1])
print('\n')
print(con_1)
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print('\n')
print(con_2)
print('\n')

tensor([[-0.6390, -0.2546, -0.3666, -2.0194, -0.0479],
        [-1.3206, -2.0099, -0.1652,  0.8156, -2.4552]])
tensor([[-2.3227, -0.7441,  0.8031,  1.6413,  0.4196],
        [ 1.0009, -0.9307,  2.4704, -0.5341, -2.1565],
        [-1.2133, -1.3283,  3.4193, -0.6795, -0.8030]])


tensor([[-0.6390, -0.2546, -0.3666, -2.0194, -0.0479],
        [-1.3206, -2.0099, -0.1652,  0.8156, -2.4552],
        [-2.3227, -0.7441,  0.8031,  1.6413,  0.4196],
        [ 1.0009, -0.9307,  2.4704, -0.5341, -2.1565],
        [-1.2133, -1.3283,  3.4193, -0.6795, -0.8030]])


tensor([[ 0.0418, -0.1727,  0.4614],
        [-0.2010,  0.9183,  0.4632]])
tensor([[-0.5928, -0.3126,  1.1546,  1.4157, -1.1385],
        [ 0.0969,  0.8252,  1.1585, -1.2019,  0.0853]])


tensor([[ 0.0418, -0.1727,  0.4614, -0.5928, -0.3126,  1.1546,  1.4157, -1.1385],
        [-0.2010,  0.9183,  0.4632,  0.0969,  0.8252,  1.1585, -1.2019,  0.0853]])




## Adding Dimensions to Tensors

In [33]:
#Adds a dimension of 1 along a specified index
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1,1)
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:,2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c,2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.4932, 0.2364, 0.7401, 0.0137],
         [0.2722, 0.9645, 0.2632, 0.4770],
         [0.8928, 0.4172, 0.6952, 0.0981]],

        [[0.4221, 0.0498, 0.0223, 0.3289],
         [0.9493, 0.5973, 0.6329, 0.4858],
         [0.9511, 0.2140, 0.2617, 0.6990]]])


tensor([[0.7401, 0.2632, 0.6952],
        [0.0223, 0.6329, 0.2617]])
torch.Size([2, 3])


tensor([[[0.7401],
         [0.2632],
         [0.6952]],

        [[0.0223],
         [0.6329],
         [0.2617]]])
torch.Size([2, 3, 1])


## AutoGrad

In [34]:
#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [35]:
#Now if we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [36]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
None
True
True
False


In [37]:
#Let's walk in through one last example
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [38]:
m1 = torch.ones(5,5)
m2 = torch.zeros(5,5)
#Perform element-wise multiplaction 
mul = torch.mul(m1,m2)
#Another way to perform element-wise multiplaction 
mul_another = m1*m2
print(mul)
print(mul_another)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


### Boolean operations on tensors

In [42]:
t = torch.tensor([3,4,5])
t>3, (t>3).int()

(tensor([False,  True,  True]), tensor([0, 1, 1], dtype=torch.int32))