# Weight Initializations

In [1]:
import torch
import torch.nn as nn

In [2]:
layer=nn.Linear(5,5)
layer.weight

Parameter containing:
tensor([[ 0.2078, -0.3760,  0.1101, -0.2030,  0.4268],
        [ 0.0605, -0.3327, -0.0074,  0.4246, -0.1040],
        [ 0.2475,  0.4026,  0.3328,  0.2427, -0.0518],
        [ 0.2186,  0.2592,  0.1623, -0.3387, -0.2311],
        [ 0.3839, -0.1536, -0.2720,  0.0789, -0.1979]], requires_grad=True)

In [3]:
layer.weight.data

tensor([[ 0.2078, -0.3760,  0.1101, -0.2030,  0.4268],
        [ 0.0605, -0.3327, -0.0074,  0.4246, -0.1040],
        [ 0.2475,  0.4026,  0.3328,  0.2427, -0.0518],
        [ 0.2186,  0.2592,  0.1623, -0.3387, -0.2311],
        [ 0.3839, -0.1536, -0.2720,  0.0789, -0.1979]])

#### Initialize weights from a uniform distribution

In [5]:
nn.init.uniform_(layer.weight, a=0, b=3)

Parameter containing:
tensor([[2.5019, 1.8907, 2.6448, 2.2385, 1.1996],
        [2.7993, 2.9588, 0.1801, 1.7922, 2.5986],
        [1.4525, 2.5382, 0.1595, 0.9795, 0.6863],
        [0.4982, 0.8649, 2.8514, 2.5145, 2.0633],
        [0.1145, 1.6884, 1.7922, 1.8022, 0.4393]], requires_grad=True)

#### Normal distribution

In [6]:
nn.init.normal_(layer.weight,mean=0,std=1)

Parameter containing:
tensor([[ 1.0943, -0.3267,  2.2693, -0.7540,  0.4579],
        [-0.1376, -0.2715,  0.1138,  1.3099,  0.5850],
        [-0.4884,  1.0451,  0.8172,  0.0957,  0.5815],
        [-0.8085, -2.0696,  1.0201,  0.7417, -1.7293],
        [-1.5003,  0.0384, -0.1607, -0.4126,  0.9503]], requires_grad=True)

In [7]:
nn.init.normal_(layer.weight,mean=0,std=0.2)

Parameter containing:
tensor([[-0.1435,  0.1518,  0.2681, -0.0735,  0.0544],
        [-0.2377, -0.1084, -0.1018, -0.2526,  0.2871],
        [-0.1581, -0.0927, -0.3010, -0.4115, -0.0858],
        [-0.2431,  0.0748,  0.1786, -0.2693, -0.3267],
        [-0.1584, -0.0358,  0.2019, -0.3176, -0.2323]], requires_grad=True)

#### Constant distribution for initializing bias

In [8]:
nn.init.constant_(layer.bias,0)
layer.bias

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

#### Xavier uniform and Xavier normal